//! DOM and box tree structures
//!
//! This module contains the tree data structures that represent the document:
//! - **DOM tree**: The parsed HTML document structure
//! - **Box tree**: The CSS box tree generated from the DOM
//! - **Fragment tree**: The positioned, sized fragments ready for painting
//!
//! # Architecture
//!
//! FastRender uses a three-tree architecture:
//!
//! 1. **DOM Tree** (`DomNode`):
//!    - Represents the parsed HTML document
//!    - Immutable after parsing
//!    - Contains element names, attributes, text content
//!
//! 2. **Box Tree** (`BoxNode`):
//!    - Generated from DOM + computed styles
//!    - Represents CSS boxes before layout
//!    - Anonymous boxes are created here
//!    - Not yet positioned or sized
//!
//! 3. **Fragment Tree** (`FragmentNode`):
//!    - Generated by layout algorithms
//!    - Fully positioned and sized
//!    - Ready for painting
//!    - Contains final coordinates and dimensions
//!
//! # Module Organization
//!
//! This module will contain:
//! - `dom.rs` - DOM node types
//! - `box_tree.rs` - Box tree types (minimal stub for W2.T07, full impl in W2.T01)
//! - `fragment.rs` - Fragment tree types (minimal stub for W2.T07, full impl in W2.T03)
//!
//! # Example
//!
//! ```rust,ignore
//! use fastrender::tree::{DomNode, BoxNode, FragmentNode};
//!
//! // Parse HTML -> DOM tree
//! let dom_tree = parse_html("<div>Hello</div>");
//!
//! // Generate boxes -> Box tree
//! let box_tree = generate_boxes(&dom_tree, &styles);
//!
//! // Run layout -> Fragment tree
//! let fragment_tree = layout(&box_tree, viewport_size);
//!
//! // Paint fragments
//! paint(&fragment_tree);
//! ```

// Minimal stub implementations for W2.T07 (FormattingContext trait)
// Full implementations will be provided by W2.T01 (BoxNode) and W2.T03 (Fragment)
pub mod box_tree;
pub mod fragment;

pub use box_tree::{BoxNode, ComputedStyle, FormattingContextType};
pub use fragment::Fragment;
